repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.71.0
    hooks:
      - id: terraform_docs
        args: ["--output-file", "README.md", "./"]
      - id: terraform_fmt
      - id: terraform_validate
